version: '2.4'
services:
  postgres:
    container_name: pgsql
    image: phamzito/postgres:main
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  lavalink:
    container_name: lavalink
    image: phamzito/lavalink:main
    restart: always
    ports:
      - '2333:2333'
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
volumes:
  postgres-data:
    external: true
