version: '2.4'
services:
  postgres:
    container_name: pgsql
    image: phamzito/postgres:main
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    external: true
